### ISSUE TITLE
[Bug] Two `:constants` definitions in out domain file when there is already a `:constants` definition in the in domain file

### ISSUE THREAD

**Issue by Rezenders** [remaro-network/dlToPlanning#38]
Hi @tobiaswjohn,

When converting a domain file that contains a `:constants` definition, the generated domain file contains two `:constants` definitions. For example:

Snippet in file:
```pddl
(:types
  waypoint
  action
  numerical-object
)

(:constants
  wpf - waypoint
  1.0_decimal 0.8_decimal 0.0_decimal - numerical-object
)
```

Snippet out file:
```pddl
(:constants
  wpf - waypoint
  1.0_decimal 0.8_decimal 0.0_decimal - numerical-object
)

(:types
  waypoint
  action
  numerical-object
)

(:constants
  1.0_decimal ERROR_string a_move c_camera c_headlamp  ... - object
)
```

**Comment by tobiaswjohn** [comment]
I see why this does not work at the moment (we do not parse ':constants' at the moment at all). I will fix this.

**Comment by tobiaswjohn** [comment]
should be fixed now

**Comment by Rezenders** [comment]
@tobiaswjohn  It seems that this issue is back.

When I convert the following pddl files:
- [suave_domain_extended.pddl](https://github.com/kas-lab/suave_planta/blob/1451245e965d749ca3eb843390f3af2fa7da2c70/pddl/suave_domain_extended.pddl)
- [suave_problem_extended.pddl](https://github.com/kas-lab/suave_planta/blob/1451245e965d749ca3eb843390f3af2fa7da2c70/pddl/suave_problem_extended.pddl)

With the ontology:
- [suave_extended.owl](https://github.com/kas-lab/suave_planta/blob/1451245e965d749ca3eb843390f3af2fa7da2c70/owl/suave_extended.owl)

Using the command:
```Bash
OWLToPDDL.sh --owl=owl/suave_extended.owl --tBox --inDomain=pddl/suave_domain_extended.pddl --outDomain=pddl/suave_domain_extended_test.pddl --aBox --inProblem=pddl/suave_problem_extended.pddl --outProblem=pddl/suave_problem_extended_test.pddl --add-num-comparisons --replace-output
```

I get the domain file:

```PDDL
(define (domain suave)
  (:requirements
    :strips
    :typing
    :adl
    :negative-preconditions
    :derived-predicates
    :existential-preconditions
    :disjunctive-preconditions
  )


  
	(:types
		pipeline
		robot
		numerical-object
	)

	(:constants
		0.25_decimal 1.0_decimal - numerical-object 
		ERROR_string a_inspect_pipeline a_recharge_battery a_search_pipeline battery_level c_thruster_1 c_thruster_2 c_thruster_3 c_thruster_4 c_thruster_5 c_thruster_6 f_follow_pipeline f_generate_search_path f_maintain_motion false_boolean fd_all_thrusters fd_follow_pipeline fd_recharge_path fd_recover_thrusters fd_spiral_high fd_spiral_low fd_spiral_medium fd_unground generate_recharge_path obs_battery_level obs_water_visibility performance qa_inspect_efficiency_high qa_motion_efficiency_degraded qa_motion_efficiency_normal qa_performance_zero qa_search_efficiency_high qa_search_efficiency_low qa_search_efficiency_medium qa_water_visibility_high qa_water_visibility_low qa_water_visibility_medium true_boolean water_visibility - object
	)

  (:predicates
    (pipeline_found ?p - pipeline)
    (pipeline_inspected ?p - pipeline)

    (robot_started ?r - robot)
    (robot_not_started ?r - robot)

    (inferred-battery_charged ?r)

		(Action ?x)
		(Component ?x)
		(Function ?x)
		(FunctionDesign ?x)
		(QAvalue ?x)
		(QualityAttributeType ?x)
		(c_status ?x ?y)
		(differentFrom ?x ?y)
		(f_active ?x ?y)
		(fdBetterUtility ?x ?y)
		(fd_realisability ?x ?y)
		(fd_utility ?x ?y)
		(functionGrounding ?x ?y)
		(hasQAestimation ?x ?y)
		(inferred-Action ?x)
		(inferred-C_status ?x ?y)
		(inferred-Component ?x)
		(inferred-DifferentFrom ?x ?y)
		(inferred-F_active ?x ?y)
		(inferred-FdBetterUtility ?x ?y)
		(inferred-Fd_realisability ?x ?y)
		(inferred-Fd_utility ?x ?y)
		(inferred-Function ?x)
		(inferred-FunctionDesign ?x)
		(inferred-FunctionGrounding ?x ?y)
		(inferred-HasQAestimation ?x ?y)
		(inferred-Inconsistent)
		(inferred-IsQAtype ?x ?y)
		(inferred-QAvalue ?x)
		(inferred-Qa_has_value ?x ?y)
		(inferred-QualityAttributeType ?x)
		(inferred-RequiresC ?x ?y)
		(inferred-RequiresF ?x ?y)
		(inferred-SameAs ?x ?y)
		(inferred-SolvesF ?x ?y)
		(isQAtype ?x ?y)
		(lessThan ?x ?y)
		(qa_has_value ?x ?y)
		(requiresC ?x ?y)
		(requiresF ?x ?y)
		(sameAs ?x ?y)
		(solvesF ?x ?y)
		(equalTo ?x ?y)
  )


(:derived (inferred-Action ?x) 
	(and
		(Action ?x)
	)
)


(:derived (inferred-Action ?x) 
	(exists (?y)
 		(and
			(inferred-RequiresF ?x ?y)
		)
	)
 )


(:derived (inferred-C_status ?x ?y) 
	(and
		(c_status ?x ?y)
	)
)


(:derived (inferred-Component ?x) 
	(and
		(Component ?x)
	)
)


(:derived (inferred-Component ?x) 
	(exists (?y)
 		(and
			(inferred-C_status ?x ?y)
		)
	)
 )


(:derived (inferred-Component ?y) 
	(exists (?x)
 		(and
			(inferred-RequiresC ?x ?y)
		)
	)
 )


(:derived (inferred-DifferentFrom ?x ?y) 
	(and
		(differentFrom ?x ?y)
	)
)


(:derived (inferred-F_active ?f ?true_boolean) 
	(and
		(= ?true_boolean true_boolean)
		(exists (?fd)
 			(and
				(inferred-Function ?f)
				(inferred-FunctionDesign ?fd)
				(not (= ?fd fd_unground))
				(inferred-SolvesF ?fd ?f)
				(inferred-FunctionGrounding ?f ?fd)
			)
		)
 	)
 )


(:derived (inferred-F_active ?x ?y) 
	(and
		(f_active ?x ?y)
	)
)


(:derived (inferred-FdBetterUtility ?fd_better ?fd) 
	(exists (?x_better ?f ?x)
 		(and
			(inferred-Fd_utility ?fd_better ?x_better)
			(inferred-Function ?f)
			(inferred-FunctionDesign ?fd)
			(inferred-FunctionDesign ?fd_better)
			(lessThan ?x ?x_better)
			(inferred-SolvesF ?fd ?f)
			(inferred-Fd_utility ?fd ?x)
			(inferred-SolvesF ?fd_better ?f)
		)
	)
 )


(:derived (inferred-FdBetterUtility ?x ?y) 
	(and
		(fdBetterUtility ?x ?y)
	)
)


(:derived (inferred-Fd_realisability ?fd ?false_boolean) 
	(and
		(= ?false_boolean false_boolean)
		(exists (?c)
 			(and
				(inferred-RequiresC ?fd ?c)
				(inferred-Component ?c)
				(inferred-C_status ?c ERROR_string)
			)
		)
 	)
 )


(:derived (inferred-Fd_realisability ?fd1 ?false_boolean) 
	(and
		(= ?false_boolean false_boolean)
		(exists (?eqa ?eqav ?mqa ?mqav)
 			(and
				(inferred-FunctionDesign ?fd1)
				(inferred-HasQAestimation ?fd1 ?eqa)
				(inferred-IsQAtype ?eqa water_visibility)
				(inferred-Qa_has_value ?eqa ?eqav)
				(inferred-QAvalue ?mqa)
				(= ?mqa obs_water_visibility)
				(inferred-Qa_has_value ?mqa ?mqav)
				(inferred-IsQAtype ?mqa water_visibility)
				(lessThan ?mqav ?eqav)
			)
		)
 	)
 )


(:derived (inferred-Fd_realisability ?x ?y) 
	(and
		(fd_realisability ?x ?y)
	)
)


(:derived (inferred-Fd_utility ?fd ?qav) 
	(exists (?f ?qa)
 		(and
			(inferred-Function f_follow_pipeline)
			(inferred-FunctionDesign ?fd)
			(inferred-SolvesF ?fd ?f)
			(inferred-HasQAestimation ?fd ?qa)
			(inferred-IsQAtype ?qa performance)
			(inferred-Qa_has_value ?qa ?qav)
		)
	)
 )


(:derived (inferred-Fd_utility ?fd ?qav) 
	(exists (?f ?qa)
 		(and
			(inferred-Function f_generate_search_path)
			(inferred-FunctionDesign ?fd)
			(inferred-SolvesF ?fd ?f)
			(inferred-HasQAestimation ?fd ?qa)
			(inferred-IsQAtype ?qa performance)
			(inferred-Qa_has_value ?qa ?qav)
		)
	)
 )


(:derived (inferred-Fd_utility ?fd ?qav) 
	(exists (?f ?qa)
 		(and
			(inferred-Function f_maintain_motion)
			(inferred-FunctionDesign ?fd)
			(inferred-SolvesF ?fd ?f)
			(inferred-HasQAestimation ?fd ?qa)
			(inferred-IsQAtype ?qa performance)
			(inferred-Qa_has_value ?qa ?qav)
		)
	)
 )


(:derived (inferred-Fd_utility ?x ?y) 
	(and
		(fd_utility ?x ?y)
	)
)


(:derived (inferred-Function ?x) 
	(and
		(Function ?x)
	)
)


(:derived (inferred-Function ?x) 
	(exists (?y)
 		(and
			(inferred-F_active ?x ?y)
		)
	)
 )


(:derived (inferred-Function ?x) 
	(exists (?y)
 		(and
			(inferred-FunctionGrounding ?x ?y)
		)
	)
 )


(:derived (inferred-Function ?y) 
	(exists (?x)
 		(and
			(inferred-RequiresF ?x ?y)
		)
	)
 )


(:derived (inferred-Function ?y) 
	(exists (?x)
 		(and
			(inferred-SolvesF ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?x) 
	(and
		(FunctionDesign ?x)
	)
)


(:derived (inferred-FunctionDesign ?x) 
	(exists (?y)
 		(and
			(inferred-FdBetterUtility ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?x) 
	(exists (?y)
 		(and
			(inferred-Fd_realisability ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?x) 
	(exists (?y)
 		(and
			(inferred-Fd_utility ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?x) 
	(exists (?y)
 		(and
			(inferred-HasQAestimation ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?x) 
	(exists (?y)
 		(and
			(inferred-RequiresC ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?x) 
	(exists (?y)
 		(and
			(inferred-SolvesF ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?y) 
	(exists (?x)
 		(and
			(inferred-FdBetterUtility ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionDesign ?y) 
	(exists (?x)
 		(and
			(inferred-FunctionGrounding ?x ?y)
		)
	)
 )


(:derived (inferred-FunctionGrounding ?x ?y) 
	(and
		(functionGrounding ?x ?y)
	)
)


(:derived (inferred-HasQAestimation ?x ?y) 
	(and
		(hasQAestimation ?x ?y)
	)
)


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-C_status ?x ?y)
			(inferred-C_status ?x ?z)
			(not (= ?y ?z))
		)
	)
 )


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-F_active ?x ?y)
			(inferred-F_active ?x ?z)
			(not (= ?y ?z))
		)
	)
 )


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-Fd_realisability ?x ?y)
			(inferred-Fd_realisability ?x ?z)
			(not (= ?y ?z))
		)
	)
 )


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-Fd_utility ?x ?y)
			(inferred-Fd_utility ?x ?z)
			(not (= ?y ?z))
		)
	)
 )


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-IsQAtype ?x ?y)
			(inferred-IsQAtype ?x ?z)
			(= ?y ?z)
		)
	)
 )


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-Qa_has_value ?x ?y)
			(inferred-Qa_has_value ?x ?z)
			(not (= ?y ?z))
		)
	)
 )


(:derived (inferred-Inconsistent ) 
	(exists (?x ?y ?z)
 		(and
			(inferred-SolvesF ?x ?y)
			(inferred-SolvesF ?x ?z)
			(= ?y ?z)
		)
	)
 )


(:derived (inferred-IsQAtype ?x ?y) 
	(and
		(isQAtype ?x ?y)
	)
)


(:derived (inferred-QAvalue ?x) 
	(and
		(QAvalue ?x)
	)
)


(:derived (inferred-QAvalue ?x) 
	(exists (?y)
 		(and
			(inferred-IsQAtype ?x ?y)
		)
	)
 )


(:derived (inferred-QAvalue ?x) 
	(exists (?y)
 		(and
			(inferred-Qa_has_value ?x ?y)
		)
	)
 )


(:derived (inferred-QAvalue ?y) 
	(exists (?x)
 		(and
			(inferred-HasQAestimation ?x ?y)
		)
	)
 )


(:derived (inferred-Qa_has_value ?x ?y) 
	(and
		(qa_has_value ?x ?y)
	)
)


(:derived (inferred-QualityAttributeType ?x) 
	(and
		(QualityAttributeType ?x)
	)
)


(:derived (inferred-QualityAttributeType ?y) 
	(exists (?x)
 		(and
			(inferred-IsQAtype ?x ?y)
		)
	)
 )


(:derived (inferred-RequiresC ?x ?y) 
	(and
		(requiresC ?x ?y)
	)
)


(:derived (inferred-RequiresF ?x ?y) 
	(and
		(requiresF ?x ?y)
	)
)


(:derived (inferred-SameAs ?x ?y) 
	(and
		(sameAs ?x ?y)
	)
)


(:derived (inferred-SolvesF ?fd_unground ?f) 
	(and
		(= ?fd_unground fd_unground)
		(and
			(inferred-Function ?f)
			(inferred-FunctionDesign fd_unground)
		)
	)
 )


(:derived (inferred-SolvesF ?x ?y) 
	(and
		(solvesF ?x ?y)
	)
)



  (:derived (inferred-battery_charged ?r)
    (and
      (exists (?mqa ?mqav) 
        (and
          (= ?mqa obs_battery_level)
          (inferred-Qa_has_value ?mqa ?mqav)
          (inferred-IsQAtype ?mqa battery_level)
          (lessThan 0.25_decimal ?mqav)
        )
      )
    )
  ) 
  
  (:action start_robot
    :parameters (?r - robot)
    :precondition (and
      (robot_not_started ?r)
    )
    :effect (and
      (not (robot_not_started ?r))
      (robot_started ?r)
    )
  )

  (:action reconfigure1
    :parameters (?f ?fd_goal)
    :precondition (and
      (Function ?f)
      (inferred-SolvesF ?fd_goal ?f)
      (FunctionDesign ?fd_goal)
      (not (inferred-Fd_realisability ?fd_goal false_boolean))
      (not
        (exists (?fd)
          (and
            (inferred-SolvesF ?fd ?f)
            (FunctionDesign ?fd)
            (functionGrounding ?f ?fd)
          )
        )
      )
    )
    :effect (and
      (functionGrounding ?f ?fd_goal)
    )
  )

  (:action reconfigure2
    :parameters (?f ?fd_initial ?fd_goal)
    :precondition (and
      (not (= ?fd_initial ?fd_goal))

      (Function ?f)
      (FunctionDesign ?fd_initial)
      (functionGrounding ?f ?fd_initial)

      (inferred-SolvesF ?fd_goal ?f)
      (FunctionDesign ?fd_goal)
      (not (inferred-Fd_realisability ?fd_goal false_boolean))
    )
    :effect (and
      (not (functionGrounding ?f ?fd_initial))
      (functionGrounding ?f ?fd_goal)
    )
  )

  (:action search_pipeline
    :parameters (?p - pipeline ?r - robot)
    :precondition (and
      (robot_started ?r)
      (inferred-battery_charged ?r)
      (exists (?a ?f1 ?f2 ?fd1 ?fd2)
        (and
          (inferred-Action ?a)
          (= ?a a_search_pipeline)
          (not (= ?f1 ?f2))
          (inferred-requiresF ?a ?f1)
          (inferred-requiresF ?a ?f2)
          (inferred-F_active ?f1 true_boolean)
          (inferred-F_active ?f2 true_boolean)
          (inferred-FunctionGrounding ?f1 ?fd1)
          (inferred-FunctionGrounding ?f2 ?fd2)
          (not (inferred-Fd_realisability ?fd1 false_boolean))
          (not (inferred-Fd_realisability ?fd2 false_boolean))
          (not
            (exists (?fd1_b)
              (and
                (not (= ?fd1 ?fd1_b))
                (inferred-SolvesF ?fd1_b ?f1)
                (not (inferred-Fd_realisability ?fd1_b false_boolean))
                (inferred-FdBetterUtility  ?fd1_b ?fd1)
              )
            )
          )
          (not
            (exists (?fd2_b)
              (and
                (not (= ?fd2 ?fd2_b))
                (inferred-SolvesF ?fd2_b ?f2)
                (not (inferred-Fd_realisability ?fd2_b false_boolean))
                (inferred-FdBetterUtility  ?fd2_b ?fd2)
              )
            )
          )
        )
      )
      (not (inferred-F_active f_follow_pipeline true_boolean))
      (not (inferred-F_active generate_recharge_path true_boolean))
    )
    :effect (and
      (pipeline_found ?p)
    )
  )

  (:action inspect_pipeline
    :parameters (?p - pipeline ?r - robot)
    :precondition (and
      (robot_started ?r)
      (pipeline_found ?p)
      (inferred-battery_charged ?r)
      (exists (?a ?f1 ?f2 ?fd1 ?fd2)
        (and
          (inferred-Action ?a)
          (= ?a a_inspect_pipeline)
          (not (= ?f1 ?f2))
          (inferred-requiresF ?a ?f1)
          (inferred-requiresF ?a ?f2)
          (inferred-F_active ?f1 true_boolean)
          (inferred-F_active ?f2 true_boolean)
          (inferred-FunctionGrounding ?f1 ?fd1)
          (inferred-FunctionGrounding ?f2 ?fd2)
          (not (inferred-Fd_realisability ?fd1 false_boolean))
          (not (inferred-Fd_realisability ?fd2 false_boolean))
          (not
            (exists (?fd1_b)
              (and
                (not (= ?fd1 ?fd1_b))
                (inferred-SolvesF ?fd1_b ?f1)
                (not (inferred-Fd_realisability ?fd1_b false_boolean))
                (inferred-FdBetterUtility  ?fd1_b ?fd1)
              )
            )
          )
          (not
            (exists (?fd2_b)
              (and
                (not (= ?fd2 ?fd2_b))
                (inferred-SolvesF ?fd2_b ?f2)
                (not (inferred-Fd_realisability ?fd2_b false_boolean))
                (inferred-FdBetterUtility  ?fd2_b ?fd2)
              )
            )
          )
        )
      )
      (not (inferred-F_active f_generate_search_path true_boolean))
      (not (inferred-F_active generate_recharge_path true_boolean))
    )
    :effect (and
      (pipeline_inspected ?p)
    )
  )

  (:action recharge_battery
    :parameters (?r - robot)
    :precondition (and
      (robot_started ?r)
      (exists (?a ?f1 ?f2 ?fd1 ?fd2)
        (and
          (inferred-Action ?a)
          (= ?a a_recharge_battery)
          (not (= ?f1 ?f2))
          (inferred-requiresF ?a ?f1)
          (inferred-requiresF ?a ?f2)
          (inferred-F_active ?f1 true_boolean)
          (inferred-F_active ?f2 true_boolean)
          (inferred-FunctionGrounding ?f1 ?fd1)
          (inferred-FunctionGrounding ?f2 ?fd2)
          (not (inferred-Fd_realisability ?fd1 false_boolean))
          (not (inferred-Fd_realisability ?fd2 false_boolean))
        )
      )
      (not (inferred-F_active f_generate_search_path true_boolean))
      (not (inferred-F_active f_follow_pipeline true_boolean))
    )
    :effect (and
      (qa_has_value obs_battery_level 1.0_decimal)
    )
  )

)
```

And problem file:

```PDDL
(define (problem example-auv)
  (:domain suave)

  (:objects 
    pipeline - pipeline 
    bluerov - robot 
    0.0_decimal 0.25_decimal 0.5_decimal 0.75_decimal 1.0_decimal 1.25_decimal 2.25_decimal 3.25_decimal - numerical-object 
)

  (:init
    ;(qa_has_value obs_water_visibility 2.5_decimal)
    (qa_has_value obs_battery_level 1.0_decimal)
    (robot_not_started bluerov)
    
    (equalTo 0.0_decimal 0.0_decimal)
    (equalTo 0.25_decimal 0.25_decimal)
    (equalTo 0.5_decimal 0.5_decimal)
    (equalTo 0.75_decimal 0.75_decimal)
    (equalTo 1.0_decimal 1.0_decimal)
    (equalTo 1.25_decimal 1.25_decimal)
    (equalTo 2.25_decimal 2.25_decimal)
    (equalTo 3.25_decimal 3.25_decimal)
    (lessThan 0.0_decimal 0.25_decimal)
    (lessThan 0.0_decimal 0.5_decimal)
    (lessThan 0.0_decimal 0.75_decimal)
    (lessThan 0.0_decimal 1.0_decimal)
    (lessThan 0.0_decimal 1.25_decimal)
    (lessThan 0.0_decimal 2.25_decimal)
    (lessThan 0.0_decimal 3.25_decimal)
    (lessThan 0.25_decimal 0.5_decimal)
    (lessThan 0.25_decimal 0.75_decimal)
    (lessThan 0.25_decimal 1.0_decimal)
    (lessThan 0.25_decimal 1.25_decimal)
    (lessThan 0.25_decimal 2.25_decimal)
    (lessThan 0.25_decimal 3.25_decimal)
    (lessThan 0.5_decimal 0.75_decimal)
    (lessThan 0.5_decimal 1.0_decimal)
    (lessThan 0.5_decimal 1.25_decimal)
    (lessThan 0.5_decimal 2.25_decimal)
    (lessThan 0.5_decimal 3.25_decimal)
    (lessThan 0.75_decimal 1.0_decimal)
    (lessThan 0.75_decimal 1.25_decimal)
    (lessThan 0.75_decimal 2.25_decimal)
    (lessThan 0.75_decimal 3.25_decimal)
    (lessThan 1.0_decimal 1.25_decimal)
    (lessThan 1.0_decimal 2.25_decimal)
    (lessThan 1.0_decimal 3.25_decimal)
    (lessThan 1.25_decimal 2.25_decimal)
    (lessThan 1.25_decimal 3.25_decimal)
    (lessThan 2.25_decimal 3.25_decimal)
    
    (Action a_inspect_pipeline)
    (Action a_recharge_battery)
    (Action a_search_pipeline)
    (Component c_thruster_1)
    (Component c_thruster_2)
    (Component c_thruster_3)
    (Component c_thruster_4)
    (Component c_thruster_5)
    (Component c_thruster_6)
    (Function f_follow_pipeline)
    (Function f_generate_search_path)
    (Function f_maintain_motion)
    (Function generate_recharge_path)
    (FunctionDesign fd_all_thrusters)
    (FunctionDesign fd_follow_pipeline)
    (FunctionDesign fd_recharge_path)
    (FunctionDesign fd_recover_thrusters)
    (FunctionDesign fd_spiral_high)
    (FunctionDesign fd_spiral_low)
    (FunctionDesign fd_spiral_medium)
    (FunctionDesign fd_unground)
    (QAvalue obs_battery_level)
    (QAvalue obs_water_visibility)
    (QAvalue qa_inspect_efficiency_high)
    (QAvalue qa_motion_efficiency_degraded)
    (QAvalue qa_motion_efficiency_normal)
    (QAvalue qa_performance_zero)
    (QAvalue qa_search_efficiency_high)
    (QAvalue qa_search_efficiency_low)
    (QAvalue qa_search_efficiency_medium)
    (QAvalue qa_water_visibility_high)
    (QAvalue qa_water_visibility_low)
    (QAvalue qa_water_visibility_medium)
    (QualityAttributeType battery_level)
    (QualityAttributeType performance)
    (QualityAttributeType water_visibility)
    (hasQAestimation fd_all_thrusters qa_motion_efficiency_normal)
    (hasQAestimation fd_follow_pipeline qa_inspect_efficiency_high)
    (hasQAestimation fd_recover_thrusters qa_motion_efficiency_degraded)
    (hasQAestimation fd_spiral_high qa_search_efficiency_high)
    (hasQAestimation fd_spiral_high qa_water_visibility_high)
    (hasQAestimation fd_spiral_low qa_search_efficiency_low)
    (hasQAestimation fd_spiral_low qa_water_visibility_low)
    (hasQAestimation fd_spiral_medium qa_search_efficiency_medium)
    (hasQAestimation fd_spiral_medium qa_water_visibility_medium)
    (hasQAestimation fd_unground qa_performance_zero)
    (isQAtype obs_battery_level battery_level)
    (isQAtype obs_water_visibility water_visibility)
    (isQAtype qa_inspect_efficiency_high performance)
    (isQAtype qa_motion_efficiency_degraded performance)
    (isQAtype qa_motion_efficiency_normal performance)
    (isQAtype qa_performance_zero performance)
    (isQAtype qa_search_efficiency_high performance)
    (isQAtype qa_search_efficiency_low performance)
    (isQAtype qa_search_efficiency_medium performance)
    (isQAtype qa_water_visibility_high water_visibility)
    (isQAtype qa_water_visibility_low water_visibility)
    (isQAtype qa_water_visibility_medium water_visibility)
    (qa_has_value qa_inspect_efficiency_high 1.0_decimal)
    (qa_has_value qa_motion_efficiency_degraded 0.75_decimal)
    (qa_has_value qa_motion_efficiency_normal 1.0_decimal)
    (qa_has_value qa_performance_zero 0.0_decimal)
    (qa_has_value qa_search_efficiency_high 1.0_decimal)
    (qa_has_value qa_search_efficiency_low 0.25_decimal)
    (qa_has_value qa_search_efficiency_medium 0.5_decimal)
    (qa_has_value qa_water_visibility_high 3.25_decimal)
    (qa_has_value qa_water_visibility_low 1.25_decimal)
    (qa_has_value qa_water_visibility_medium 2.25_decimal)
    (requiresC fd_all_thrusters c_thruster_1)
    (requiresC fd_all_thrusters c_thruster_2)
    (requiresC fd_all_thrusters c_thruster_3)
    (requiresC fd_all_thrusters c_thruster_4)
    (requiresC fd_all_thrusters c_thruster_5)
    (requiresC fd_all_thrusters c_thruster_6)
    (requiresF a_inspect_pipeline f_follow_pipeline)
    (requiresF a_inspect_pipeline f_maintain_motion)
    (requiresF a_recharge_battery f_maintain_motion)
    (requiresF a_recharge_battery generate_recharge_path)
    (requiresF a_search_pipeline f_generate_search_path)
    (requiresF a_search_pipeline f_maintain_motion)
    (solvesF fd_all_thrusters f_maintain_motion)
    (solvesF fd_follow_pipeline f_follow_pipeline)
    (solvesF fd_recharge_path generate_recharge_path)
    (solvesF fd_recover_thrusters f_maintain_motion)
    (solvesF fd_spiral_high f_generate_search_path)
    (solvesF fd_spiral_low f_generate_search_path)
    (solvesF fd_spiral_medium f_generate_search_path)
  )

  (:goal 
    (and
      (robot_started bluerov)
      (pipeline_found pipeline)
      (pipeline_inspected pipeline)
    )
  )
)
```

**Comment by tobiaswjohn** [comment]
@Rezenders I think you discovered a new issue. This issue is about two declarations of a constant in the domain but your new issue is about declaring a constant in the domain and the problem file.
